# Subscriber parameters 
aruco_topic: /follower/aruco_single/position
aruco_queue: 100

# Publisher parameters
cmd_vel_topic: /follower/cmd_vel
cmd_vel_queue: 100

# Speeds
linear_vel: 0.1
angular_vel: 0.5
